'use strict';
export const BOX_COUNT = 'BOX_COUNT';
export const BOX_LOAD = 'BOX_LOAD';
export const BOX_LOAD_SUCCESS = 'BOX_LOAD_SUCCESS';
export const BOX_LOAD_FAIL = 'BOX_LOAD_FAIL';
export const BOX_ID_LOAD = 'BOX_ID_LOAD';
export const BOX_ID_LOAD_SUCCESS = 'BOX_ID_LOAD_SUCCESS';
export const BOX_ID_LOAD_FAIL = 'BOX_ID_LOAD_FAIL';
export const BOX_ID_PUSH_LOAD = 'BOX_ID_PUSH_LOAD';
export const BOX_ID_PUSH_SUCCESS = 'BOX_ID_PUSH_SUCCESS';
export const BOX_ID_PUSH_FAIL = 'BOX_ID_PUSH_FAIL';
export const BOX_ID_LOAD_INFO = 'BOX_ID_LOAD_INFO';
export const BOX_ID_LOAD_INFO_SUCCESS = 'BOX_ID_LOAD_INFO_SUCCESS';
export const BOX_ID_LOAD_INFO_FAIL = 'BOX_ID_LOAD_INFO_FAIL';
// Auth
export const LOAD_AUTH = 'LOAD_AUTH';
export const CREATE_AUTH_LOAD = 'SIGNUP_LOAD';
export const CREATE_AUTH_SUCCESS = 'CREATE_AUTH_SUCCESS';
export const CREATE_AUTH_FAIL = 'CREATE_AUTH_FAIL';
export const LOGIN_LOAD = 'LOGIN_LOAD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_LOAD = 'LOGOUT_LOAD';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
// location
export const CITY_LOAD = "CITY_LOAD";
export const CITY_SUCCESS = "CITY_SUCCESS";
export const CITY_FAIL = "CITY_FAIL";
export const DISTRICT_LOAD = "DISTRICT_LOAD";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FAIL = "DISTRICT_FAIL";
// verify
export const GET_CODE_LOAD = "GET_CODE_LOAD";
export const GET_CODE_SUCCESS = "GET_CODE_SUCCESS";
export const GET_CODE_FAIL = "GET_CODE_FAIL";
export const VERIFY_LOAD = "VERIFY_LOAD";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";
// box require auth
export const BOX_REQUIRE_LOGIN_SHOW = "BOX_REQUIRE_LOGIN_SHOW";
export const BOX_REQUIRE_LOGIN_HIDE = "BOX_REQUIRE_LOGIN_HIDE";
export const BOX_REQUIRE_VERIFY_SHOW = "BOX_REQUIRE_VERIFY_SHOW";
export const BOX_REQUIRE_VERIFY_HIDE = "BOX_REQUIRE_VERIFY_HIDE";
// product
export const PRODUCT_COUNT = "PRODUCT_COUNT";
export const PRODUCT_LOAD = 'PRODUCT_LOAD';
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL';
export const PRODUCT_PUSH = 'PRODUCT_PUSH';
export const PRODUCT_PUSH_SUCCESS = 'PRODUCT_PUSH_SUCCESS';
export const PRODUCT_PUSH_FAIL = 'PRODUCT_PUSH_FAIL';
export const PRODUCT_ID_LOAD = "PRODUCT_ID_LOAD";
export const PRODUCT_ID_LOAD_SUCCESS = "PRODUCT_ID_LOAD_SUCCESS";
export const PRODUCT_ID_LOAD_FAIL = "PRODUCT_ID_LOAD_FAIL";
// sale
export const SALE_GET_LOAD = "SALE_GET_LOAD";
export const SALE_GET_SUCCESS = "SALE_GET_SUCCESS";
export const SALE_GET_FAIL = "SALE_GET_FAIL";
// Card
export const LOAD_CART = "LOAD_CART";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_CART_ID = "ADD_CART_ID";
export const CART_CREATE_LOAD = "CART_CREATE_LOAD";
export const CART_CREATE_SUCCESS = "CART_CREATE_SUCCESS";
export const CART_CREATE_FAIL = "CART_CREATE_FAIL";
export const CART_GET_LOAD = "CART_GET_LOAD";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";
export const CART_PUSH_LOAD = "CART_PUSH_LOAD";
export const CART_PUSH_SUCCESS = "CART_PUSH_SUCCESS";
export const CART_PUSH_FAIL = "CART_PUSH_FAIL";
export const CART_DESTROY_LOAD = "CART_DESTROY_LOAD";
export const CART_DESTROY_SUCCESS = "CART_DESTROY_SUCCESS";
export const CART_DESTROY_FAIL = "CART_DESTROY_FAIL";
export const CART_CAPNHAT_LOAD = "CART_CAPNHAT_LOAD";
export const CART_CAPNHAT_SUCCESS = "CART_CAPNHAT_SUCCESS";
export const CART_CAPNHAT_FAIL = "CART_CAPNHAT_FAIL";
export const SHIP_PING_INFO = "SHIP_PING_INFO";
export const SHIP_PING_INFO_SUCCESS = "SHIP_PING_INFO_SUCCESS";
export const SHIP_PING_INFO_FAIL = "SHIP_PING_INFO_FAIL";
export const PAYMENT_METHOD = "PAYMENT_METHOD";
export const PAYMENT_METHOD_SUCCESS = "PAYMENT_METHOD_SUCCESS";
export const PAYMENT_METHOD_FAIL = "PAYMENT_METHOD_FAIL";
// order
export const PHISHIP_LOAD = "PHISHIP_LOAD";
export const PHISHIP_SUCCESS = "PHISHIP_SUCCESS";
export const PHISHIP_FAIL = "PHISHIP_FAIL";
